# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea86875278bb0e96c434154a47a747db920b478fd631dfba75d358f80071e12ff0cf0573e9f7cac9861a51a5279e7788286c9283c5927a641aaad8084f0d6aeb

test:
  secret_key_base: d6ab2e036b988679717d3ac83f0ef1bbf0c46adca842768fcde095c69f9ba106bfc3af24ca767bf78dfa3aaa32793903dcb0234d577b60122d9a12aa868e88cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
